name = "Nguhcraft"
author = "Ætérnal"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c243d1ff7c58dfdb3743465917ae15bb6f5ac938a717e09926082b830cb70743"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.7"]
