name = "Nguhcraft"
author = "Ætérnal"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ecb27f321b29722cc215ed93cdf4146f0891d7a5fd6de5fa94835b2218b613c"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.7"]
