name = "Nguhcraft"
author = "Ætérnal"
version = "2.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f0b7bf9b48bf85eed0afdf7a312404f98ba8dfc825ba26bd73825c5669ffd0d"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.7"]
